### ISSUE TITLE
what $provide.value does?

### ISSUE THREAD

**Issue by sukrosono** [megalord/testing-standards#1]
this is merely a question, what $provide.value('otherService', otherServiceMock); really does in testing.
I m really new on unit testing, would you explain it to me?
I m stuck on my first unit test, i dont know how to mock properly, i got many dependency on my controller to test :worried:

**Comment by player-two** [comment]
Hi @brutalcrozt

`$provide.value()` is a way to register a service with the provider.  When performing dependency injection, angular's injector will consult the provider to find the service for a given name.

While you can use `$provide.value()` for your controller unit test, I suggest using [`$controller`](https://docs.angularjs.org/api/ngMock/service/$controller) instead.  You can see an example of that in this repo:
https://github.com/megalord/testing-standards/blob/master/src/controller.spec.js#L24

The second argument (called `locals` in the docs) let's you specify a map of the service names and their mocked values.  That's where you can specify the mocks.

Hope this helps!

**Comment by sukrosono** [comment]
thanks @megalord but should we test the smallest things as possible?
I thought you already describe chai and sinon on their `.md` , i still new and i think just a mess when know the lib is so many, why use `jasmine` not enough? why we need sinon, chai , mocha and sinon-chai? 
can you help me dude, i really confuse what should i do?
how properly mock dependencies? my controller got so many dependencies. :confused:

**Comment by player-two** [comment]
In the setup I have used, there are definitely a lot of libraries in place, and it can certainly get confusing easily (that's why I put this guide together in the first place).

You can use Jasmine if you want.  I cannot directly tell you what to use because it depends on your goals.  I have found the combination in this guide to satisfy my needs, where I need an API with a large surface area.

Did you get a chance to look at the link I put in the previous comment?  That is a very simple example of how to mock dependencies for a controller.  You will need to define the mock objects for your dependencies and inject them using `$controller`.

**Comment by sukrosono** [comment]
@megalord my view based on `ui-router` also, now i am facing some problem.
on the beforeEach my ctrl fine, but in the `it` block it got undefined.
